weight_initial_value: 1.
weight_update_iters:  [ 1, 3000, 8000, 13000,  15000]
weight_update_values: [1.,  0.1, 0.01, 0.001, 0.0001]

depth_ratio: 0.6

max_pixel_shift_ratio: 0.05
normalize_loss: true
log_space: true
log_scale: 20.0
reduction: 'mean'
